use_frameworks!

platform :ios, '8.0'

target 'SSSlidingSelector_Example' do
  pod 'SSSlidingSelector', :path => '../'

  target 'SSSlidingSelector_Tests' do
    inherit! :search_paths

    
  end
end
